name: Zanzar CI
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
  
jobs:
  test:
    name: Test iOS
    runs-on: macos-latest
    steps:
      - name: Checkout to main
        uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          brew install swiftlint
          brew install xcbeautify

      - name: Run SwiftLint
        run: swiftlint lint

      - name: Show project info
        run: |
          xcodebuild -version
          xcodebuild -project ./ZanzarProject/ZanzarProject.xcodeproj -list
          xcodebuild -project ./ZanzarProject/ZanzarProject.xcodeproj -scheme ZanzarProject -showdestinations

      - name: Create Config.xcconfig
        run: |
          cat > ZanzarProject/Config.xcconfig <<EOF
          ZANZAR_API_BASE_URL = http://127.0.0.1:3000
          EOF

      - name: Run and test project
        run: |
          set -o pipefail && xcodebuild -project ./ZanzarProject/ZanzarProject.xcodeproj -scheme ZanzarProject -destination 'platform=iOS Simulator,name=iPhone 17,OS=latest,arch=arm64' test | xcbeautify